apiVersion: v1
description: A Helm chart for Generic Clevertech Apps
home: https://github.com/clevertech/kubernetes-charts
icon: https://www.clevertech.biz/static/media/logo.d14a672e.svg
keywords:
- generic-app
- nodejs
- nginx
- react
maintainers:
- email: devops@cleverbuild.biz
  name: Clevertech
name: generic-app
sources:
- https://github.com/clevertech/kubernetes-charts
version: 0.1.24
