# Default values for generic-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  healthcheck: {}
  # healthcheck: /healthz
  podAnnotations: {}
  serviceAccountName: {}
  #serviceAccountName: ...
  #healthcheckCommand: # Use this in alternative to "healthcheck"
  #  - "echo"
  # periodSeconds: 10 # Optional
  # timeoutSeconds: 1 # Optional
  # successThreshold: 1 # Optional
  # failureThreshold: 3 # Optional
  # command: ["yarn"] # Optional: Allows the specification of a start command
  # args: ["run", "start"] # Optional: Allows the specification start command parameters
  # strategy: # Optional: Specify Recreate instead of rolling update, useful for background jobs
  #   type: Recreate
  env: {}
    # - name: NODE_ENV
    #   value: production
  envFrom: {}
    # - secretRef:
    #     name: nginx-config

  podAntiaffinity:
    enabled: true
  initialDelaySeconds: 10 # optional; defaults to 10
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  minReadySeconds: 1 # optional; defaults to 1
replicaCount: 1
hpa:
  enabled: false
  maxReplicas: 2
  minReplicas: 1
  cpuUtilization:
    targetPercentage: 70
  memoryUtilization:
    targetPercentage: 70


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

secrets: {}
  # - data:
  #     EMAIL_PASSWORD: abracadabra@example.com
  #   name: example
  #   type: Opaque

service:
# `LoadBalancer` / `ClusterIP` / `""` are available options
# Use `ClusterIP` without ports for a background process
  type: ""
  #acm: arn:aws:acm:....
  #internal: true # to create an internal loadbalancer
  name: api
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumes: []
  # - name: secrets-store-inline
  #   csi:
  #     driver: secrets-store.csi.k8s.io
  #     readOnly: true
  #     volumeAttributes:
  #       secretProviderClass: "vault-application"


# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
  # - name: secrets-store-inline
  #   mountPath: "/mnt/secrets-store"
  #   readOnly: true